# Generated by Django 2.1.3 on 2019-03-02 12:46

from django.db import migrations, models
import django.db.models.deletion
import professors.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=15)),
                ('slug', models.SlugField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='professors.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=2, validators=[professors.validators.grade_system])),
                ('class_grade', models.CharField(max_length=2, null=True, validators=[professors.validators.grade_system])),
                ('difficulty', models.IntegerField(validators=[professors.validators.difficulty])),
                ('class_num', models.IntegerField(validators=[professors.validators.class_num])),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.CharField(default='Anonymous', max_length=200)),
                ('review', models.CharField(max_length=10000)),
                ('quarter', models.IntegerField(validators=[professors.validators.quarter])),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_major', to='professors.Major')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='professors.Professor')),
            ],
            options={
                'ordering': ('class_grade',),
            },
        ),
    ]
