# Generated by Django 2.1.3 on 2019-01-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
                ('difficulty', models.IntegerField()),
                ('class_num', models.IntegerField()),
                ('major', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=10000)),
                ('year_taken', models.DateField()),
                ('quarter', models.IntegerField()),
            ],
        ),
    ]
