# Generated by Django 2.1.3 on 2019-01-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='year_taken',
            field=models.DateField(null=True),
        ),
    ]
