# Generated by Django 2.1.3 on 2019-03-08 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_auto_20190307_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.Major'),
        ),
    ]
