# Generated by Django 2.1.3 on 2019-01-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_auto_20190102_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('class_grade',)},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='grade',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='class_grade',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
