# Generated by Django 2.1.3 on 2019-01-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_auto_20190103_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=15)),
            ],
        ),
    ]
