# Generated by Django 2.1.3 on 2019-01-05 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='professors.Major'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
