# Generated by Django 2.1.3 on 2019-01-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_auto_20190104_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_major', to='professors.Major'),
        ),
    ]
