# Generated by Django 2.1.4 on 2019-01-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_auto_20190106_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
