# Generated by Django 2.1.3 on 2019-02-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0008_major_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
