# Generated by Django 2.1.3 on 2019-03-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0009_professor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
