# Generated by Django 2.1.3 on 2019-03-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0010_auto_20190301_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
