# Generated by Django 2.1.3 on 2019-03-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0011_auto_20190301_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='year_taken',
        ),
    ]
